# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{suggester}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Ching"]
  s.date = %q{2011-04-04}
  s.default_executable = %q{suggester_server}
  s.description = %q{Extensible, cache-based auto-suggest server for ruby. Includes refresh and replication support out of the box.}
  s.email = %q{ching.jeff@gmail.com}
  s.executables = ["suggester_server"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/suggester_server",
    "config/database.yml.example",
    "lib/array_bsearch.rb",
    "lib/suggester.rb",
    "lib/suggester/client.rb",
    "lib/suggester/handlers.rb",
    "lib/suggester/handlers/active_record.rb",
    "lib/suggester/handlers/base.rb",
    "lib/suggester/handlers/helpers/normalization.rb",
    "lib/suggester/handlers/helpers/refresh.rb",
    "lib/suggester/handlers/marshal.rb",
    "lib/suggester/handlers/yaml.rb",
    "lib/suggester/server.rb",
    "pkg/suggester-0.0.1.gem",
    "pkg/suggester-0.0.2.gem",
    "suggester.gemspec",
    "test/fixtures/books.sql",
    "test/fixtures/marshal.marshal",
    "test/fixtures/yaml.yml",
    "test/functional/basic_test.rb",
    "test/test_helper.rb",
    "test/unit/active_record_handler_test.rb",
    "test/unit/marshal_handler_test.rb",
    "test/unit/yaml_handler_test.rb"
  ]
  s.homepage = %q{http://github.com/chingor13/suggester}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Extensible, cache-based auto-suggest server for ruby.}
  s.test_files = [
    "test/functional/basic_test.rb",
    "test/test_helper.rb",
    "test/unit/active_record_handler_test.rb",
    "test/unit/marshal_handler_test.rb",
    "test/unit/yaml_handler_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<vegas>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<vegas>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<vegas>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

